name: 🧪 Validação ou Teste de Dados
description: Solicite verificação de dados, KPIs ou integrações.
title: '[VALIDAÇÃO] Breve descrição do que precisa ser validado'
labels: ['validação', 'dados']
body:
  - type: textarea
    id: oque
    attributes:
      label: O que precisa ser validado?
      placeholder: "Ex: Verificar se os dados de leads da semana estão sendo carregados corretamente no BI."
    validations:
      required: true

  - type: textarea
    id: como
    attributes:
      label: Como é feita a validação atualmente?
      placeholder: "Ex: Conferência com a planilha original enviada pelo setor comercial."
    validations:
      required: false

  - type: textarea
    id: contexto
    attributes:
      label: Contexto adicional
      placeholder: "Ex: Suspeita de duplicidade em alguns registros."
    validations:
      required: false
