name: 🔌 Integração com API ou Base de Dados
description: Solicitação de integração entre sistemas internos e externos.
title: '[INTEGRAÇÃO] Breve descrição da integração'
labels: ['integração', 'dados']
body:
  - type: textarea
    id: origem
    attributes:
      label: Origem dos dados
      placeholder: "Ex: API RD Station, Banco de dados ERP"
    validations:
      required: true

  - type: textarea
    id: destino
    attributes:
      label: Destino dos dados
      placeholder: "Ex: Banco PostgreSQL, Planilha do Google Sheets"
    validations:
      required: true

  - type: textarea
    id: tipo-dados
    attributes:
      label: Quais dados devem ser integrados?
      placeholder: "Ex: Nome do lead, status de venda, data de conversão"
    validations:
      required: true

  - type: textarea
    id: frequencia
    attributes:
      label: Qual a frequência dessa integração?
      placeholder: "Ex: A cada 30 minutos, diariamente"
    validations:
      required: false

  - type: textarea
    id: contexto
    attributes:
      label: Contexto adicional
      placeholder: "Ex: Existe autenticação por token, precisamos armazenar logs"
    validations:
      required: false
